server:
  port: 8080

spring:
  datasource:
    username: root
    password: Saurabh.10
    url: jdbc:mysql://accounterp.cb67gu1lvxk6.us-west-2.rds.amazonaws.com:3306/accountERP

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        generate_statistics: false